INSERT INTO PRODUCT(ID, NAME) VALUES ('1', 'Ticket 1 Day')
INSERT INTO PRODUCT(ID, NAME) VALUES ('2', 'Ticket 2 Day')
INSERT INTO PRODUCT(ID, NAME) VALUES ('3', 'Ticket 3 Day')
INSERT INTO PRODUCT(ID, NAME) VALUES ('4', 'Ticket 4 Day')
